// generated by scripts/from-site.js — do not edit
/* eslint-disable */
const F: Record<string, unknown> = {
  "JP/2026-10-10.ja.json": require('./app/v1/JP/2026-10-10.ja.json'),
  "KR/2026-10-05.ko.json": require('./app/v1/KR/2026-10-05.ko.json'),
  "KR/2026-10-06.ko.json": require('./app/v1/KR/2026-10-06.ko.json'),
  "KR/2026-10-07.ko.json": require('./app/v1/KR/2026-10-07.ko.json'),
  "KR/2026-10-08.ko.json": require('./app/v1/KR/2026-10-08.ko.json'),
  "KR/2026-10-09.ko.json": require('./app/v1/KR/2026-10-09.ko.json'),
  "KR/2026-10-10.en.json": require('./app/v1/KR/2026-10-10.en.json'),
  "KR/2026-10-10.ja.json": require('./app/v1/KR/2026-10-10.ja.json'),
  "KR/2026-10-10.ko.json": require('./app/v1/KR/2026-10-10.ko.json'),
  "US/2026-10-09.en.json": require('./app/v1/US/2026-10-09.en.json'),
  "US/2026-10-10.en.json": require('./app/v1/US/2026-10-10.en.json'),
  "breaking.json": require('./app/v1/breaking.json'),
  "glossary/en.json": require('./app/v1/glossary/en.json'),
  "glossary/ja.json": require('./app/v1/glossary/ja.json'),
  "glossary/ko.json": require('./app/v1/glossary/ko.json'),
  "index.json": require('./app/v1/index.json'),
};
export default F;
