const {_android}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const {execFileSync}=require('node:child_process');const fs=require('node:fs');const assert=require('node:assert/strict');
const adb=process.env.ADB_PATH;if(!adb)throw Error('Set ADB_PATH');
const args=['-P','5038','-s','emulator-5580'];const run=(...xs)=>execFileSync(adb,[...args,...xs],{encoding:'utf8',timeout:45000});
const results=[];let device,page;
async function attach(){device=(await _android.devices({port:5038,omitDriverInstall:true})).find(x=>x.serial()==='emulator-5580');assert.ok(device);const view=device.webViews().find(x=>x.pkg()==='kr.dailydrop.app')||await device.waitForEvent('webview',{predicate:x=>x.pkg()==='kr.dailydrop.app',timeout:30000});page=await view.page();page.setDefaultTimeout(60000);await page.waitForFunction(()=>document.querySelector('#reader')?.contentDocument?.body?.innerText?.length>10);}
async function restart(){run('shell','am','force-stop','kr.dailydrop.app');await device.close();run('shell','am','start','-W','-n','kr.dailydrop.app/.MainActivity');await attach();}
async function waitFrame(fn){await page.frameLocator('#reader').locator('body').evaluate(fn);}
function pass(s){results.push(s);console.log('PASS',s)}
(async()=>{try{
 await attach();if(!process.env.REMOTE_ONLY){assert.equal(page.url(),'https://localhost/');assert.match(await page.locator('#edition-label').innerText(),/제3호/);assert.equal(await page.locator('#push').isDisabled(),true);assert.equal(await page.locator('#push').innerText(),'알림 준비 중');pass('native launch, third edition, unconfigured push disabled');
 let fr=page.frameLocator('#reader');await fr.locator('[data-id="nuri"] h2').click();await page.waitForFunction(()=>!document.querySelector('#reader').contentDocument.querySelector('#ov').hidden);await fr.locator('#ov .term').first().click();await page.waitForFunction(()=>!document.querySelector('#reader').contentDocument.querySelector('#tip').hidden);run('shell','input','keyevent','4');await page.waitForFunction(()=>document.querySelector('#reader').contentDocument.querySelector('#tip').hidden&&!document.querySelector('#reader').contentDocument.querySelector('#ov').hidden);run('shell','input','keyevent','4');await page.waitForFunction(()=>document.querySelector('#reader').contentDocument.querySelector('#ov').hidden);pass('article and term open; Android back closes term then article');
 if(await page.locator('#save').getAttribute('aria-pressed')!=='true')await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#save').getAttribute('aria-pressed')==='true');
 await page.locator('[data-tab="glossary"]').click();await page.frameLocator('#reader').locator('input').fill('금리');assert.match(await page.frameLocator('#reader').locator('body').innerText(),/금리/);run('shell','input','keyevent','4');await page.waitForFunction(()=>document.querySelector('[data-tab="today"]').hasAttribute('aria-current'));pass('glossary search and native back to latest');
 run('shell','svc','wifi','disable');run('shell','svc','data','disable');await restart();await page.locator('[data-tab="saved"]').click();await page.locator('.edition-card').waitFor();assert.match(await page.locator('#saved-list').innerText(),/2026-10-07/);await page.locator('.edition-card').click();await page.waitForFunction(()=>document.querySelector('#reader').contentDocument?.body?.innerText?.includes('누리호'));pass('native Preferences bookmark and bundled reading survive offline process restart');
 run('shell','am','start','-W','-a','android.intent.action.VIEW','-d','https://dailydrop.kr/2026-10-06/','-n','kr.dailydrop.app/.MainActivity');await page.waitForFunction(()=>document.querySelector('#edition-label').innerText.includes('제2호'));pass('explicit HTTPS Android intent opens second edition offline');
 for(let i=0;i<3;i++){await page.reload();await page.locator('#edition-label').filter({hasText:'제'}).waitFor();await page.locator('#push').filter({hasText:'알림 준비 중'}).waitFor();}pass('three native WebView reloads finish initialization');}
 run('shell','svc','wifi','enable');run('shell','svc','data','enable');
 await page.route('https://dailydrop.kr/**',r=>r.request().url().endsWith('/editions.json')?r.fulfill({json:{editions:[{date:'2026-10-08',no:4,blurb:'Synthetic native QA',html:'https://dailydrop.kr/2026-10-08/index.html'}]},headers:{'access-control-allow-origin':'*'}}):r.fulfill({contentType:'text/html',body:'<html><head><title>QA only</title></head><body><h1>Native offline QA fixture</h1></body></html>',headers:{'access-control-allow-origin':'*'}}));
 await page.reload();await page.locator('#notice').filter({hasText:'새 호'}).waitFor();await page.locator('[data-tab="today"]').click();await page.waitForFunction(()=>document.querySelector('#reader').contentDocument?.body?.innerText?.includes('Native offline QA fixture'));assert.match(await page.locator('#reader').getAttribute('src'),/_capacitor_file_/);await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#save').getAttribute('aria-pressed')==='true');pass('synthetic remote edition stored through native Filesystem and rendered');
 run('shell','svc','wifi','disable');run('shell','svc','data','disable');await restart();await page.waitForFunction(()=>document.querySelector('#reader').contentDocument?.body?.innerText?.includes('Native offline QA fixture'));await page.locator('[data-tab="saved"]').click();assert.match(await page.locator('#saved-list').innerText(),/2026-10-08/);pass('native remote HTML and saved state survive offline process restart');
 fs.writeFileSync('qa/android-results.json',JSON.stringify({android:'16 / API36 AOSP arm64 emulator',webView:'133.0.6943.137',passed:results,limits:['Remote edition test uses intercepted synthetic HTML/index.','No physical-device or actual push-delivery test.','Explicit intent is not verification of automatic domain App Links.']},null,2));
}finally{
 if(device)await device.close().catch(()=>{});run('shell','svc','wifi','enable');run('shell','svc','data','enable');
}
})().catch(e=>{fs.writeFileSync('qa/android-failure.json',JSON.stringify({passed:results,error:String(e.stack)},null,2));console.error(e);process.exitCode=1});
