// TV-only UI strings in every TV language — ko ja en de fr es pt it nl zh-TW hi (the rest comes from shared/site.json via shared/i18n.ts, so labels match the web).
import { strings as siteStrings } from './shared/i18n';

const TV: Record<string, Record<string, string>> = {
  ko: {
    viewingPast: '지난 호 · 제{n}호 — 뒤로 버튼을 누르면 최신호로 돌아갑니다',
    readerHint: '▲▼ 스크롤   ◀▶ 용어 고르기   OK 뜻 보기   뒤로 닫기',
    readerHintNoTerms: '▲▼ 스크롤   뒤로 닫기',
    termHint: '이 기사의 용어 {n}개 — ◀▶로 고르고 OK',
    ambientHint: '아무 버튼이나 누르면 돌아갑니다',
    ambient: '자동 넘김 화면',
    ambientP: '최신호 화면에서 리모컨을 만지지 않으면 헤드라인을 전체 화면으로 차례로 보여 줍니다.',
    theme: '화면',
    dark: '다크',
    paper: '종이',
    more: '이 호의 다른 면',
    readOnWeb: '전체 기사·링크는 dailydropnewspaper.com 에서',
    sec: '{n}초',
    min: '{n}분',
    latestTag: '최신',
    langs: '언어',
    breakingEmpty: '지금 들어온 속보가 없습니다.',
    termWhy: '이 기사에서는',
    inside: '짧게 보는 오늘', // edition index heading (.index h4)
    newEdition: '새 호 · 제{n}호',
    errBody: '문제가 생겼습니다. OK를 누르면 다시 불러옵니다.',
    errOk: 'OK',
  },
  ja: {
    viewingPast: '過去の号 · 第{n}号 — 戻るボタンで最新号に戻ります',
    readerHint: '▲▼ スクロール   ◀▶ 用語を選ぶ   OK 意味   戻る 閉じる',
    readerHintNoTerms: '▲▼ スクロール   戻る 閉じる',
    termHint: 'この記事の用語 {n}件 — ◀▶で選んでOK',
    ambientHint: 'いずれかのボタンで戻ります',
    ambient: 'おまかせ表示',
    ambientP: '最新号の画面でリモコンを操作しないと、見出しを全画面で順番に表示します。',
    theme: '画面',
    dark: 'ダーク',
    paper: '紙',
    more: 'この号のほかの面',
    readOnWeb: '全文・リンクは dailydropnewspaper.com で',
    sec: '{n}秒',
    min: '{n}分',
    latestTag: '最新',
    langs: '言語',
    breakingEmpty: '現在、速報はありません。',
    termWhy: 'この記事では',
    inside: '短く見るきょう', // edition index heading (.index h4)
    newEdition: '新しい号 · 第{n}号',
    errBody: '問題が発生しました。OKで再読み込みします。',
    errOk: 'OK',
  },
  en: {
    viewingPast: 'Past edition · No. {n} — press Back to return to the latest',
    readerHint: '▲▼ Scroll   ◀▶ Pick a term   OK Define   Back Close',
    readerHintNoTerms: '▲▼ Scroll   Back Close',
    termHint: '{n} terms in this story — ◀▶ then OK',
    ambientHint: 'Press any button to return',
    ambient: 'Lean-back mode',
    ambientP: 'When the remote is left alone on the Latest page, headlines cycle full-screen.',
    theme: 'Display',
    dark: 'Dark',
    paper: 'Paper',
    more: 'More in this edition',
    readOnWeb: 'Full articles and links at dailydropnewspaper.com',
    sec: '{n} s',
    min: '{n} min',
    latestTag: 'Latest',
    langs: 'Languages',
    breakingEmpty: 'No breaking news right now.',
    termWhy: 'In this story',
    inside: 'Inside', // edition index heading (.index h4)
    newEdition: 'New edition · No. {n}',
    errBody: 'Something went wrong. Press OK to reload.',
    errOk: 'OK',
  },
  de: {
    viewingPast: 'Frühere Ausgabe · Nr. {n} — Zurück drücken für die aktuelle Ausgabe',
    readerHint: '▲▼ Blättern   ◀▶ Begriff wählen   OK Bedeutung   Zurück Schließen',
    readerHintNoTerms: '▲▼ Blättern   Zurück Schließen',
    termHint: '{n} Begriffe in diesem Artikel — ◀▶, dann OK',
    ambientHint: 'Beliebige Taste drücken, um zurückzukehren',
    ambient: 'Zurücklehn-Modus',
    ambientP: 'Wird die Fernbedienung auf der aktuellen Seite nicht benutzt, laufen die Schlagzeilen bildschirmfüllend durch.',
    theme: 'Darstellung',
    dark: 'Dunkel',
    paper: 'Papier',
    more: 'Mehr in dieser Ausgabe',
    readOnWeb: 'Vollständige Artikel und Links auf dailydropnewspaper.com',
    sec: '{n} s',
    min: '{n} min',
    latestTag: 'Aktuell',
    langs: 'Sprachen',
    breakingEmpty: 'Gerade keine Eilmeldungen.',
    termWhy: 'In diesem Artikel',
    inside: 'Außerdem', // edition index heading (.index h4)
    newEdition: 'Neue Ausgabe · Nr. {n}',
    errBody: 'Etwas ist schiefgelaufen. OK drücken, um neu zu laden.',
    errOk: 'OK',
  },
  fr: {
    viewingPast: 'Édition précédente · N° {n} — appuyez sur Retour pour revenir à la dernière',
    readerHint: '▲▼ Défiler   ◀▶ Choisir un terme   OK Définition   Retour Fermer',
    readerHintNoTerms: '▲▼ Défiler   Retour Fermer',
    termHint: '{n} termes dans cet article — ◀▶ puis OK',
    ambientHint: 'Appuyez sur une touche pour revenir',
    ambient: 'Mode détente',
    ambientP: 'Si la télécommande reste inactive sur la dernière édition, les titres défilent en plein écran.',
    theme: 'Affichage',
    dark: 'Sombre',
    paper: 'Papier',
    more: 'Aussi dans cette édition',
    readOnWeb: 'Articles complets et liens sur dailydropnewspaper.com',
    sec: '{n} s',
    min: '{n} min',
    latestTag: 'Dernière',
    langs: 'Langues',
    breakingEmpty: 'Aucune alerte pour le moment.',
    termWhy: 'Dans cet article',
    inside: 'À l\'intérieur', // edition index heading (.index h4)
    newEdition: 'Nouvelle édition · N° {n}',
    errBody: 'Un problème est survenu. Appuyez sur OK pour recharger.',
    errOk: 'OK',
  },
  es: {
    viewingPast: 'Edición anterior · N.º {n} — pulsa Atrás para volver a la última',
    readerHint: '▲▼ Desplazar   ◀▶ Elegir término   OK Definición   Atrás Cerrar',
    readerHintNoTerms: '▲▼ Desplazar   Atrás Cerrar',
    termHint: '{n} términos en esta noticia — ◀▶ y OK',
    ambientHint: 'Pulsa cualquier botón para volver',
    ambient: 'Modo pasivo',
    ambientP: 'Si no tocas el mando en la última edición, los titulares pasan a pantalla completa.',
    theme: 'Pantalla',
    dark: 'Oscuro',
    paper: 'Papel',
    more: 'Más en esta edición',
    readOnWeb: 'Noticias completas y enlaces en dailydropnewspaper.com',
    sec: '{n} s',
    min: '{n} min',
    latestTag: 'Última',
    langs: 'Idiomas',
    breakingEmpty: 'No hay noticias de última hora ahora.',
    termWhy: 'En esta noticia',
    inside: 'Hoy, en corto', // edition index heading (.index h4)
    newEdition: 'Nueva edición · N.º {n}',
    errBody: 'Algo salió mal. Pulsa OK para recargar.',
    errOk: 'OK',
  },
  pt: {
    viewingPast: 'Edição anterior · N.º {n} — prima Voltar para a mais recente',
    readerHint: '▲▼ Rolar   ◀▶ Escolher termo   OK Significado   Voltar Fechar',
    readerHintNoTerms: '▲▼ Rolar   Voltar Fechar',
    termHint: '{n} termos nesta matéria — ◀▶ e OK',
    ambientHint: 'Pressione qualquer botão para voltar',
    ambient: 'Modo descanso',
    ambientP: 'Sem usar o controle na edição mais recente, as manchetes passam em tela cheia.',
    theme: 'Tela',
    dark: 'Escuro',
    paper: 'Papel',
    more: 'Mais nesta edição',
    readOnWeb: 'Matérias completas e links em dailydropnewspaper.com',
    sec: '{n} s',
    min: '{n} min',
    latestTag: 'Recente',
    langs: 'Idiomas',
    breakingEmpty: 'Nenhuma notícia urgente agora.',
    termWhy: 'Nesta matéria',
    inside: 'Também hoje', // edition index heading (.index h4)
    newEdition: 'Nova edição · N.º {n}',
    errBody: 'Algo deu errado. Pressione OK para recarregar.',
    errOk: 'OK',
  },
  it: {
    viewingPast: 'Edizione precedente · N. {n} — premi Indietro per tornare all’ultima',
    readerHint: '▲▼ Scorri   ◀▶ Scegli un termine   OK Significato   Indietro Chiudi',
    readerHintNoTerms: '▲▼ Scorri   Indietro Chiudi',
    termHint: '{n} termini in questo articolo — ◀▶ poi OK',
    ambientHint: 'Premi un tasto qualsiasi per tornare',
    ambient: 'Modalità relax',
    ambientP: 'Se il telecomando resta fermo sull’ultima edizione, i titoli scorrono a schermo intero.',
    theme: 'Schermo',
    dark: 'Scuro',
    paper: 'Carta',
    more: 'Altro in questa edizione',
    readOnWeb: 'Articoli completi e link su dailydropnewspaper.com',
    sec: '{n} s',
    min: '{n} min',
    latestTag: 'Ultima',
    langs: 'Lingue',
    breakingEmpty: 'Nessuna ultim’ora al momento.',
    termWhy: 'In questo articolo',
    inside: 'In pagina', // edition index heading (.index h4)
    newEdition: 'Nuova edizione · N. {n}',
    errBody: 'Qualcosa è andato storto. Premi OK per ricaricare.',
    errOk: 'OK',
  },
  nl: {
    viewingPast: 'Eerdere editie · Nr. {n} — druk op Terug voor de nieuwste',
    readerHint: '▲▼ Scrollen   ◀▶ Term kiezen   OK Betekenis   Terug Sluiten',
    readerHintNoTerms: '▲▼ Scrollen   Terug Sluiten',
    termHint: '{n} termen in dit artikel — ◀▶ en OK',
    ambientHint: 'Druk op een knop om terug te gaan',
    ambient: 'Achteroverleunmodus',
    ambientP: 'Als de afstandsbediening op de nieuwste editie stil ligt, lopen de koppen schermvullend voorbij.',
    theme: 'Weergave',
    dark: 'Donker',
    paper: 'Papier',
    more: 'Meer in deze editie',
    readOnWeb: 'Volledige artikelen en links op dailydropnewspaper.com',
    sec: '{n} s',
    min: '{n} min',
    latestTag: 'Nieuwste',
    langs: 'Talen',
    breakingEmpty: 'Nu geen breaking news.',
    termWhy: 'In dit artikel',
    inside: 'Verder vandaag', // edition index heading (.index h4)
    newEdition: 'Nieuwe editie · Nr. {n}',
    errBody: 'Er ging iets mis. Druk op OK om opnieuw te laden.',
    errOk: 'OK',
  },
  'zh-TW': {
    viewingPast: '過去的號 · 第{n}號 — 按返回鍵回到最新號',
    readerHint: '▲▼ 捲動   ◀▶ 選擇名詞   OK 查看釋義   返回 關閉',
    readerHintNoTerms: '▲▼ 捲動   返回 關閉',
    termHint: '本文有 {n} 個名詞 — 用 ◀▶ 選擇後按 OK',
    ambientHint: '按任意鍵返回',
    ambient: '自動輪播',
    ambientP: '在最新號頁面一段時間未操作遙控器時，以全螢幕輪流顯示頭條。',
    theme: '畫面',
    dark: '深色',
    paper: '紙張',
    more: '本號其他版面',
    readOnWeb: '完整報導與連結請見 dailydropnewspaper.com',
    sec: '{n} 秒',
    min: '{n} 分鐘',
    latestTag: '最新',
    langs: '語言',
    breakingEmpty: '目前沒有快訊。',
    termWhy: '在本文中',
    inside: '要聞速覽', // edition index heading (.index h4)
    newEdition: '新的一號 · 第{n}號',
    errBody: '發生問題。按 OK 重新載入。',
    errOk: 'OK',
  },
  hi: {
    viewingPast: 'पिछला अंक · अंक {n} — नवीनतम पर लौटने के लिए बैक दबाएँ',
    readerHint: '▲▼ स्क्रॉल   ◀▶ शब्द चुनें   OK अर्थ   बैक बंद',
    readerHintNoTerms: '▲▼ स्क्रॉल   बैक बंद',
    termHint: 'इस ख़बर में {n} शब्द — ◀▶ फिर OK',
    ambientHint: 'लौटने के लिए कोई भी बटन दबाएँ',
    ambient: 'आराम मोड',
    ambientP: 'नवीनतम पन्ने पर रिमोट न छूने पर सुर्ख़ियाँ पूरी स्क्रीन पर बारी-बारी से दिखती हैं।',
    theme: 'डिस्प्ले',
    dark: 'डार्क',
    paper: 'काग़ज़',
    more: 'इस अंक में और',
    readOnWeb: 'पूरी ख़बरें और लिंक dailydropnewspaper.com पर',
    sec: '{n} सेकंड',
    min: '{n} मिनट',
    latestTag: 'नवीनतम',
    langs: 'भाषाएँ',
    breakingEmpty: 'अभी कोई ब्रेकिंग ख़बर नहीं।',
    termWhy: 'इस ख़बर में',
    inside: 'इस अंक में', // edition index heading (.index h4)
    newEdition: 'नया अंक · अंक {n}',
    errBody: 'कुछ गड़बड़ हो गई। फिर से लोड करने के लिए OK दबाएँ।',
    errOk: 'OK',
  },
};

// App-only strings (shared/i18n.ts APP has ko/ja/en, copied from the phone app) for the other TV languages.
const APP_MORE: Record<string, Record<string, string>> = {
  de: { offline: 'Offline · gespeicherte Ausgabe', updated: 'Aktualisiert', loadFail: 'Die Ausgabe konnte nicht geladen werden.', retry: 'Erneut versuchen', notCached: 'Diese Ausgabe ist auf diesem Gerät noch nicht gespeichert. Bitte mit dem Internet verbinden.', loading: 'Lädt…', edNo: 'Nr. {n}', aboutApp: 'DailyDrop-App · die Zeitung aktualisiert sich automatisch mit der Website.', intro: 'Vorspann', introP: 'Eine kurze Animation, die beim Start den Zeitungskopf tippt.', introAnim: 'Animation', introSound: 'Schreibmaschinenklang', on: 'Ein', off: 'Aus' },
  fr: { offline: 'Hors ligne · édition enregistrée', updated: 'Mis à jour', loadFail: 'Impossible de charger l’édition.', retry: 'Réessayer', notCached: 'Cette édition n’est pas encore enregistrée sur cet appareil. Connectez-vous à Internet.', loading: 'Chargement…', edNo: 'N° {n}', aboutApp: 'Appli DailyDrop · le journal se met à jour automatiquement avec le site.', intro: 'Ouverture', introP: 'Une courte animation qui tape le titre au démarrage.', introAnim: 'Animation', introSound: 'Son de machine à écrire', on: 'Activé', off: 'Désactivé' },
  es: { offline: 'Sin conexión · edición guardada', updated: 'Actualizado', loadFail: 'No se pudo cargar la edición.', retry: 'Reintentar', notCached: 'Esta edición aún no está guardada en este dispositivo. Conéctate a internet.', loading: 'Cargando…', edNo: 'N.º {n}', aboutApp: 'App DailyDrop · el periódico se actualiza automáticamente con la web.', intro: 'Apertura', introP: 'Una breve animación que teclea la cabecera al abrir la app.', introAnim: 'Animación', introSound: 'Sonido de máquina de escribir', on: 'Sí', off: 'No' },
  pt: { offline: 'Offline · edição salva', updated: 'Atualizado', loadFail: 'Não foi possível carregar a edição.', retry: 'Tentar de novo', notCached: 'Esta edição ainda não está salva neste aparelho. Conecte-se à internet.', loading: 'Carregando…', edNo: 'N.º {n}', aboutApp: 'App DailyDrop · o jornal se atualiza automaticamente com o site.', intro: 'Abertura', introP: 'Uma breve animação que datilografa o cabeçalho ao abrir o app.', introAnim: 'Animação', introSound: 'Som de máquina de escrever', on: 'Ligado', off: 'Desligado' },
  it: { offline: 'Offline · edizione salvata', updated: 'Aggiornato', loadFail: 'Impossibile caricare l’edizione.', retry: 'Riprova', notCached: 'Questa edizione non è ancora salvata su questo dispositivo. Connettiti a Internet.', loading: 'Caricamento…', edNo: 'N. {n}', aboutApp: 'App DailyDrop · il giornale si aggiorna automaticamente con il sito.', intro: 'Apertura', introP: 'Una breve animazione che batte la testata all’avvio.', introAnim: 'Animazione', introSound: 'Suono della macchina da scrivere', on: 'Sì', off: 'No' },
  nl: { offline: 'Offline · opgeslagen editie', updated: 'Bijgewerkt', loadFail: 'De editie kon niet worden geladen.', retry: 'Opnieuw', notCached: 'Deze editie is nog niet op dit apparaat opgeslagen. Maak verbinding met internet.', loading: 'Laden…', edNo: 'Nr. {n}', aboutApp: 'DailyDrop-app · de krant wordt automatisch bijgewerkt met de website.', intro: 'Opening', introP: 'Een korte animatie die bij het starten de kop typt.', introAnim: 'Animatie', introSound: 'Typemachinegeluid', on: 'Aan', off: 'Uit' },
  'zh-TW': { offline: '離線 · 已儲存的版面', updated: '更新', loadFail: '無法載入這一號。', retry: '重試', notCached: '這一號尚未儲存在此裝置上。請連上網路。', loading: '載入中…', edNo: '第{n}號', aboutApp: 'DailyDrop 應用程式 · 版面會隨網站自動更新。', intro: '開場', introP: '開啟應用程式時以打字機打出報頭的短動畫。', introAnim: '動畫', introSound: '打字機聲音', on: '開', off: '關' },
  hi: { offline: 'ऑफ़लाइन · सहेजा गया अंक', updated: 'अपडेट', loadFail: 'अंक लोड नहीं हो सका।', retry: 'फिर कोशिश करें', notCached: 'यह अंक अभी इस डिवाइस पर सहेजा नहीं गया है। इंटरनेट से जुड़ें।', loading: 'लोड हो रहा है…', edNo: 'अंक {n}', aboutApp: 'DailyDrop ऐप · अख़बार वेबसाइट के साथ अपने-आप अपडेट होता है।', intro: 'शुरुआत', introP: 'ऐप खुलने पर मास्टहेड टाइप करने वाला छोटा एनिमेशन।', introAnim: 'एनिमेशन', introSound: 'टाइपराइटर की आवाज़', on: 'चालू', off: 'बंद' },
};

export function tvStrings(lang: string) {
  const base = String(lang || 'en').split('-')[0];
  const S = siteStrings(lang);
  const more = APP_MORE[lang] || APP_MORE[base];
  return { ...S, app: more ? { ...S.app, ...more } : S.app, tv: { ...TV.en, ...(TV[lang] || TV[base] || {}) } };
}
