import fs from 'node:fs';import path from 'node:path';import {execFileSync} from 'node:child_process';import {build} from 'esbuild';import {IN_APP_CSS} from '../src/remote-pure.mjs';
const root=path.resolve(import.meta.dirname,'..'); const stage=path.join(root,'.stage'),out=path.join(root,'web');
fs.rmSync(stage,{recursive:true,force:true});fs.mkdirSync(stage,{recursive:true});fs.cpSync(path.join(root,'source-snapshot/site'),path.join(stage,'site'),{recursive:true});
execFileSync(process.execPath,[path.join(stage,'site/build.js'),'editions.json'],{cwd:path.join(stage,'site'),stdio:'inherit'});
fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out);fs.cpSync(path.join(stage,'site/public'),path.join(out,'content'),{recursive:true});
for(const e of fs.readdirSync(path.join(out,'content'),{recursive:true})){const p=path.join(out,'content',e);if(!e.endsWith('.html'))continue;let html=fs.readFileSync(p,'utf8');html=html.replace(/<link[^>]*href="https:\/\/fonts\.googleapis\.com[^>]*>/g,'').replace(/href="\/(?!\/)/g,'href="/content/');html=html.replace(/href="(\/content\/[^"]*\/)"/g,'href="$1index.html"').replace(/href="\/content\/"/g,'href="/content/index.html"');html=html.replace('</head>',`<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'none'; object-src 'none'; base-uri 'none'"> </head>`);if(/^(\d{4}-\d{2}-\d{2}\/)?index\.html$/.test(e))html=html.replace('</head>',IN_APP_CSS+'</head>');html=html.replace('</body>','<script src="/frame.js"></script></body>');fs.writeFileSync(p,html);}
for(const f of ['index.html','app.css','frame.js'])fs.copyFileSync(path.join(root,'src',f),path.join(out,f));
const editions=JSON.parse(fs.readFileSync(path.join(root,'source-snapshot/site/editions.json'),'utf8')).filter(e=>!e.region||e.region==='KR').sort((a,b)=>a.date.localeCompare(b.date));fs.writeFileSync(path.join(out,'editions.json'),JSON.stringify(editions.map(({file,...e})=>e)));
// 빌드 시 푸시 설정 존재 여부를 플래그로 심는다: Android는 google-services.json, iOS는 aps-environment 엔타이틀먼트. 없으면 앱이 register()를 호출하지 않는다(네이티브 예외 방지).
const pushAndroid=fs.existsSync(path.join(root,'android/app/google-services.json'));
const entitlements=path.join(root,'ios/App/App/App.entitlements'); const pushIos=fs.existsSync(entitlements)&&fs.readFileSync(entitlements,'utf8').includes('aps-environment');
await build({entryPoints:[path.join(root,'src/app.mjs')],bundle:true,format:'esm',target:'es2022',outfile:path.join(out,'app.js'),define:{__PUSH_ANDROID__:String(pushAndroid),__PUSH_IOS__:String(pushIos)}});console.log('push config: android',pushAndroid,'ios',pushIos);console.log('Mobile assets built; bundled editions:',editions.length);
