import { clusterItems } from '/home/user/Playground_01/feed/worker/src/cluster.js';
import fs from 'fs';
const items = JSON.parse(fs.readFileSync('items_06.json','utf8'));
const cl = clusterItems(items);
const find = s => cl.find(c => c.items.some(i => i.title.includes(s)));
let fail = 0;
const sep = (a, b, name) => { const ok = find(a) !== find(b); console.log((ok?'PASS':'FAIL') + ' ' + name + ' separate'); if (!ok) fail++; };
const tog = (a, b, name) => { const ok = find(a) === find(b); console.log((ok?'PASS':'FAIL') + ' ' + name + ' together'); if (!ok) fail++; };
sep('BoE Interest Rate', 'SNB Interest rate', '① BoE/SNB 금리확률');
sep('Fed Interest Rate', 'ECB Interest Rate', '① Fed/ECB 금리확률');
sep('30-Day Correlation', '60-Day Correlation', '② 30/60일 상관행렬');
sep('90-Day Correlation', '120-Day Correlation', '② 90/120일 상관행렬');
sep('FX Implied Volatility', 'Commodities Implied Volatility', '③ FX/원자재 내재변동성');
sep('US Index Futures Implied', 'Top S&P 500 Stock names', '③ 지수선물/S&P종목');
sep('거래소 외국인 순매수도', '코스닥 외국인 순매수도', '④ 거래소/코스닥 외국인');
sep('거래소 외국인 순매수도', '거래소 기관 순매수도', '④ 외국인/기관');
sep("'녹색 대전환'에 10년간", '반도체 호황에 기업 여윳돈', '⑤ KITA 접미부 다른 기사');
tog('반도체 호황에 기업 여윳돈', '반도체 수출 호조로 기업 여윳돈', '⑤ 여윳돈 MBC/KITA 같은 기사');
sep('HD현대중공업 총괄부회장에', 'HD현대중공업, 누리호 성공에', 'HD현대중공업 인사/누리호');
console.log('clusters', cl.length, 'fail', fail);
