// Shape checks for the JSON API, applied to network and cached copies alike (useResource `parse`).
// The API is generated by site/build.js, but a half-deployed site, an old cached copy from a previous
// API version or a hand-edited file must never crash a screen: missing lists become empty, missing text
// becomes '', items that cannot be shown are dropped. Data that is unusable as a whole throws, so the
// caller keeps showing the last good copy instead.
import type { Block, BreakingItem, Edition, GlossaryFile, GlossaryTerm, GlossEntry, Index, Influencer, Region, Story } from './types';

const isObj = (v: unknown): v is Record<string, any> => !!v && typeof v === 'object' && !Array.isArray(v);
const str = (v: unknown): string => (typeof v === 'string' ? v : typeof v === 'number' ? String(v) : '');
const arr = <T = unknown>(v: unknown): T[] => (Array.isArray(v) ? (v as T[]) : []);
const strs = (v: unknown): string[] => arr(v).filter((x): x is string => typeof x === 'string');

export class ShapeError extends Error {}

const POPUP_KEYS = ['kick', 'title', 'what', 'why', 'me', 'a', 'b', 'say', 'src'] as const;
function popupOf(v: unknown): Story['popup'] {
  const out: Story['popup'] = {};
  if (isObj(v)) for (const k of POPUP_KEYS) if (str(v[k])) out[k] = str(v[k]);
  return out;
}

export function normEdition(raw: unknown): Edition {
  if (!isObj(raw) || !str(raw.region) || !str(raw.lang) || !str(raw.date)) throw new ShapeError('edition');
  const stories: Story[] = arr(raw.stories)
    .filter(isObj)
    .filter((s) => str(s.id) && (str(s.hl) || str(s.dek)))
    .map((s, i) => ({
      id: str(s.id),
      rank: typeof s.rank === 'number' && isFinite(s.rank) ? s.rank : 1000 + i,
      kick: str(s.kick),
      hl: str(s.hl),
      dek: str(s.dek),
      body: strs(s.body),
      popup: popupOf(s.popup),
    }));
  const blocks: Block[] = arr(raw.blocks)
    .filter(isObj)
    .map((b) => ({ type: str(b.type) || 'other', title: str(b.title) || undefined, html: str(b.html) }));
  const glossary: Record<string, GlossEntry> = {};
  if (isObj(raw.glossary)) {
    for (const [k, v] of Object.entries(raw.glossary)) {
      if (k && isObj(v) && str(v.d)) glossary[k] = { f: str(v.f), d: str(v.d), w: str(v.w) };
    }
  }
  const influencers: Influencer[] = arr(raw.influencers)
    .filter(isObj)
    .map((x) => ({ who: str(x.who), where: str(x.where) || undefined, date: str(x.date) || undefined, u: str(x.u), t: str(x.t) }));
  const m = isObj(raw.mast) ? raw.mast : {};
  return {
    v: typeof raw.v === 'number' ? raw.v : 1,
    region: str(raw.region),
    lang: str(raw.lang),
    date: str(raw.date),
    no: typeof raw.no === 'number' ? raw.no : 0,
    publishAt: str(raw.publishAt),
    url: str(raw.url),
    mast: { label: str(m.label), dateline: str(m.dateline), time: str(m.time), house: str(m.house) || undefined, ears: strs(m.ears) },
    stories,
    blocks,
    glossary,
    influencers,
    sources: arr(raw.sources),
    breaking: str(raw.breaking) || undefined,
  };
}

export function normIndex(raw: unknown): Index {
  if (!isObj(raw)) throw new ShapeError('index');
  const regions: Region[] = arr(raw.regions)
    .filter(isObj)
    .filter((r) => str(r.code) && strs(r.langs).length)
    .map((r) => {
      const editions = arr(r.editions)
        .filter(isObj)
        .filter((e) => /^\d{4}-\d{2}-\d{2}$/.test(str(e.date)))
        .map((e) => ({ date: str(e.date), no: typeof e.no === 'number' ? e.no : 0, langs: strs(e.langs) }));
      const latest = isObj(r.latest) && str(r.latest.date) ? { date: str(r.latest.date), no: typeof r.latest.no === 'number' ? r.latest.no : 0 } : editions[0] ? { date: editions[0].date, no: editions[0].no } : { date: '', no: 0 };
      const name: Record<string, string> = {};
      if (isObj(r.name)) for (const [k, v] of Object.entries(r.name)) if (typeof v === 'string') name[k] = v;
      return { code: str(r.code), name, prefix: str(r.prefix), langs: strs(r.langs), tz: str(r.tz) || 'UTC', latest, editions };
    });
  if (!regions.length) throw new ShapeError('index: no regions');
  return { v: typeof raw.v === 'number' ? raw.v : 1, generated: str(raw.generated), regions };
}

export function normGlossary(raw: unknown): GlossaryFile {
  if (!isObj(raw)) throw new ShapeError('glossary');
  const seen = new Set<string>();
  const terms: GlossaryTerm[] = [];
  for (const t of arr(raw.terms)) {
    if (!isObj(t) || !str(t.term) || seen.has(str(t.term))) continue; // FlatList key = term
    seen.add(str(t.term));
    terms.push({ term: str(t.term), f: str(t.f), d: str(t.d), w: str(t.w), region: str(t.region), date: str(t.date) });
  }
  return { terms };
}

export function normBreaking(raw: unknown): { items: BreakingItem[] } {
  if (!isObj(raw)) throw new ShapeError('breaking');
  return {
    items: arr(raw.items)
      .filter(isObj)
      .filter((x) => str(x.t) && /^https?:\/\//.test(str(x.u)))
      .map((x) => ({ t: str(x.t), u: str(x.u), s: str(x.s) || undefined, at: str(x.at) || undefined })),
  };
}
