// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');

module.exports = defineConfig([
  expoConfig,
  {
    // dist: export output; fixtures/index.ts: generated by scripts/from-site.js
    ignores: ['dist/*', 'fixtures/index.ts', 'coverage/*'],
  },
  {
    // Node build scripts and config files (not bundled into the app)
    files: ['scripts/**/*.js', '*.config.js', 'jest.setup.js'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: { __dirname: 'readonly', require: 'readonly', module: 'writable', process: 'readonly', console: 'readonly', jest: 'readonly' },
    },
  },
]);
